import { Trip } from '../types';

// 1. 导出为 Markdown 文档
export const exportTripToMarkdown = (trip: Trip): string => {
  let md = `# ${trip.title}\n\n`;
  md += `**Date:** ${trip.dates}\n`;
  md += `**Vibe:** ${trip.vibeColor.replace('bg-', '').replace('-200', '')}\n\n`;
  
  trip.itinerary.forEach(day => {
    md += `## ${day.dayLabel} (${day.date})\n\n`;
    if (day.activities.length === 0) {
        md += `*No activities planned.*\n\n`;
    }
    day.activities.forEach(act => {
      const time = act.time_range.replace(/\s/g, '');
      const costStr = act.cost ? ` ($${act.cost})` : '';
      md += `### ${time} ${act.title} ${costStr}\n`;
      md += `- **Type:** ${act.category.toUpperCase()}\n`;
      if (act.location) md += `- **Location:** ${act.location}\n`;
      if (act.description) md += `- **Note:** ${act.description}\n`;
      if (act.user_note) md += `- **User Note:** ${act.user_note}\n`;
      md += `\n`;
    });
    md += `\n---\n\n`;
  });
  
  md += `\n*Generated by Vibe Travel Planner*`;
  return md;
};

// 2. 导出为 JSON 备份
export const exportTripsToJson = (trips: Trip[]): string => {
    return JSON.stringify(trips, null, 2);
};

// 3. 通用下载函数
export const downloadFile = (filename: string, content: string, contentType: string = 'text/plain') => {
  const element = document.createElement('a');
  element.setAttribute('href', `data:${contentType};charset=utf-8,` + encodeURIComponent(content));
  element.setAttribute('download', filename);
  element.style.display = 'none';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};